name: "Tests: E2E"
on: [pull_request]
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: install playwright browsers
        run: npx playwright install --with-deps
      - name: pnpm run test:e2e
        run: pnpm run test:e2e=
